## Connect to database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/OnlyBunsDB
spring.datasource.username=postgres
spring.datasource.password=super

## Configure JPA
# Hibernate postavke
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Detaljniji logovi za Hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa=DEBUG

# Omogu?i dodatne informacije za JDBC transakcije
spring.datasource.hikari.data-source-properties.cachePrepStmts=true
spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250
spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
spring.datasource.hikari.data-source-properties.useServerPrepStmts=true

## SMTP mail server config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=onlybunsteam@gmail.com
spring.mail.password=byhm uwmv igdu gdge
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSS
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
